image: node:13

before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -t rsa 64.227.1.160 > ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod 644 ~/.ssh/known_hosts

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_parcel_master:
  stage: build
  script:
    - ls -a
    - cd ./app_mobile_ERON/
    - npm cache verify
    - nvm ls
    - nvm install --lts
    - nvm use --lts
    - npm install -g @ionic/cli
    - npm install
    - node -v
    - ionic build
  artifacts:
    expire_in: 20 mins
    paths:
      - ./app_mobile_ERON/www
  only:
    - main

deploy_main:
  stage: deploy
  variables:
    SERVEUR: "acapai@152.228.217.219"
    CHEMIN: "/var/www/app-mobile.projet-entreprise-eron.andriacapai.com/"
  script:
    - which rsync || ( apt update -y && apt install rsync -y )
    - ls -la
    - ls -la ./app_mobile_ERON/
    - /sbin/ip route|awk '/default/ { print $3 }'
    - ls ./app_mobile_ERON/www/
    - /usr/bin/rsync -r ./app_mobile_ERON/www/ ${SERVEUR}:${CHEMIN}. --exclude-from="exclude.build"
  only:
    - main