image: node:16.8.0

.before_script_template:
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -t rsa 64.227.1.160 > ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - chmod 644 ~/.ssh/known_hosts
    - npm install -g @ionic/cli
    - node -v

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - install_dependencies
  - test
  - build
  - deploy

install_dependencies:
  stage: install_dependencies
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - ./app_mobile_ERON/node_modules/
  script:
     - ls -a
     - cd ./app_mobile_ERON/
     - node -v
     - npm install -g @ionic/cli
     - npm ci
  only:
    changes:
      - package-lock.json


build_parcel_master:
  extends: .before_script_template
  stage: build
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - ./app_mobile_ERON/node_modules/
    policy: pull
  script:
    - ls -a
    - cd ./app_mobile_ERON/
    - npm cache verify
    - npm install
    - node -v
    - ionic build
  artifacts:
    expire_in: 20 mins
    paths:
      - ./app_mobile_ERON/www
  only:
    - main

test-e2e:
  image: cypress/browsers:node16.5.0-chrome97-ff96
  stage: test
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - ./app_mobile_ERON/node_modules/
    policy: pull
  script:
     - npm run ci

deploy_main:
  extends: .before_script_template
  stage: deploy
  variables:
    SERVEUR: "acapai@152.228.217.219"
    CHEMIN: "/var/www/app-mobile.projet-entreprise-eron.andriacapai.com/"
  script:
    - which rsync || ( apt update -y && apt install rsync -y )
    - ls -la
    - ls -la ./app_mobile_ERON/
    - /sbin/ip route|awk '/default/ { print $3 }'
    - ls ./app_mobile_ERON/www/
    - /usr/bin/rsync -r ./app_mobile_ERON/www/ ${SERVEUR}:${CHEMIN}. --exclude-from="exclude.build"
  only:
    - main